project_id = "kfsvgcijligxschxyuyb"

[functions.check-ai-limit]
verify_jwt = true

[functions.increment-ai-usage]
verify_jwt = true

[functions.reset-daily-limits]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-weekly-digest]
verify_jwt = false

[functions.send-milestone-email]
verify_jwt = false